### ISSUE TITLE
Необходимо исправить пути в секциях.

### ISSUE THREAD

**Issue by pecherskiy-v** [angryjack/beget-api#1]
class Domain extends Beget
{
    public $section = 'mysql/';

class Domain extends Beget
{
    public $section = 'domain/';

class Stat extends Beget
{
    public $section = 'mail/';

class Stat extends Beget
{
    public $section = 'stat/';

**Comment by angryjack** [comment]
Спасибо что заметили, исправил. 
В следующий раз создавайте МР, если есть желание помочь.

**Comment by pecherskiy-v** [comment]
Я либо вас не правильно понял либо не настолько хорошо знаком с гитом. что значит "создавайте МР", буду благодарен если разъясните.

**Comment by angryjack** [comment]
МР - merge request (запрос на слияние).

**Comment by pecherskiy-v** [comment]
изначально я и планировал это сделать но что то не получилось и я пошел по наименьшему сопротивлению).
спасибо за уточнение.
