### ISSUE TITLE
Прошу добавить метод смены php версии

### ISSUE THREAD

**Issue by pecherskiy-v** [angryjack/beget-api#2]
vendor\angryjack\beget-api\src\Section\Domain.php
/**
     * Метод изменяет версию php на переданную. Позволяет установить и снять режим cgi
     * @param $full_fqdn - полное имя домена, для которого необходимо изменить версию php;
     * @param $php_version - версия php, на которую будет произведено изменение;
     * @param $is_cgi - установить или снять режим cgi. По умолчанию имеет значение false;
     * @return \Psr\Http\Message\StreamInterface
     * @throws \Angryjack\Beget\Exception\BegetException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function changePhpVersion($full_fqdn, $php_version, $is_cgi = null)
    {
        $params = array(
            'full_fqdn' => $full_fqdn,
            'php_version' => $php_version
        );

        if (isset($is_cgi)) {
            $params['is_cgi'] = $is_cgi;
        }

        return $this->request($this->section, __FUNCTION__, $params);
    }

**Comment by angryjack** [comment]
Добавил.
